version: "3"
services:
  pyspark:
    image: "jupyter/pyspark-notebook:spark-3.5.0"
    working_dir: /home/app
    volumes:
      - C:/Users/Antonio/workspace/curso_pyspark:/home/app
      - C:/Users/Antonio/workspace/curso_pyspark/app/lib:/opt/spark/jars
    port:
      - 8888:8888 # Porta para o Jupyter Notebook
      - 4040:4040 # Porta para o Spark UI
    networks:
      - rede-local

networks:
  rede-local:
    driver: bridge